name: Automated E2E Testing
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Start server
        run: sleep 10

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          wait-on: "http://127.0.0.1:8080"
          wait-on-timeout: 60
